### ISSUE TITLE
update to 4.1.8

### ISSUE THREAD

**Issue by jurgen-kluft** [woodenToaster/cjh_4coder#1]
Hi, would you be so kind to update to 4.1.8 which is the latest 4coder release. I very much would like to take your vim layer implementation a spin and figure out how you have done this and perhaps later contribute.

**Comment by woodenToaster** [comment]
I've updated to `4.1.8` but now that 4coder is open source I've combined this custom layer with the 4coder core in another repo here: https://github.com/ChristopherHogan/cjh-4coder
